sudo: false
language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
branches:
  only:
  - dev
install:
  - yarn
script:
  - npm run generate
after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then sh deploy.sh; fi'
