name: 博客更新
on:
  push:
    branches:
      - dev

jobs:
  update-blog:
    runs-on: ubuntu-latest
    steps:
      - name: 检出
        uses: actions/checkout@master

      - name: 安装依赖
        run: yarn

      - name: 构建
        run: yarn generate

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
